- hosts: localhost
  connection: local

  vars_files:
    - vars/key.yml

  tasks:
  - name: create 755 folder
    file: path={{ item }} state=directory mode=0755
    with_items:
      - ~/.ssh

  - name: copy private key
    copy:
      content: '{{ private_key }}'
      dest: ~/.ssh/id_rsa
      mode: 0600

  - name: copy public key
    copy:
      content: '{{ public_key }}'
      dest: ~/.ssh/id_rsa.pub
