---

- hosts: localhost
  connection: local

  vars:
    - ansible_become_pass: /

  tasks:
  - name: add pacman config
    become: true
    blockinfile:
      dest: /etc/pacman.conf
      block: |
        [archlinuxfr]
        SigLevel = Never
        Server = http://repo.archlinux.fr/$arch

  - name: install packages (sudo)
    become: true
    pacman: name={{ item }}
    with_items:
      - lightdm-gtk-greeter
      - xorg
      - i3
      - rxvt-unicode
      - git
      - openssh
      - tig
      - rofi
      - dmenu
      - zsh
      - tmux
      - chromium
      - pepper-flash
      - shadowsocks
      - proxychains-ng
      - privoxy
      - linux-headers
      - broadcom-wl-dkms
      - gvim
      - python-neovim
      - autojump
      - feh
      - xclip
      - the_silver_searcher
      - mitmproxy
      - mplayer
      - thunar
      - ttf-monaco
      - ttf-inconsolata
      - wqy-microhei
      - ibus-rime
