---

- hosts: localhost
  remote_user: root
  connection: local

  vars:
    password: /
    ansible_become_pass: /
    username: linze

  tasks:
  - name: Allow 'wheel' group to have passwordless sudo
    become: true
    lineinfile:
      dest: /etc/sudoers
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) ALL'

  - name: add user
    become: true
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      groups: wheel
      update_password: on_create
