---
- name: create folder
  file: path=~/.vim/autoload state=directory

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: create soft links
  file: src=~/Coding/dot-files/.vimrc dest=~/.vimrc state=link force=yes
